import type { ThemeConfig } from '../types/modernTheme';

export const FALLBACK_THEME_CONFIG: ThemeConfig = {
  layoutStyle: 'modern',
  layoutTypography: {
    headingSizes: {
      h1: '42px',
      h2: '32px',
      h3: '24px',
    },
    headingWeight: '600',
    headingLineHeight: '1.3',
  },
  layoutSpacing: {
    sectionPaddingY: '64px',
    cardPadding: '24px',
    elementGap: '24px',
  },
  colors: {
    primary: '#0066CC',
    secondary: '#0052A3',
    accent: '#0066CC',
    background: {
      page: '#F8F9FA',
      surface: '#FFFFFF',
      elevated: '#F8F9FA',
    },
    text: {
      primary: '#1F2937',
      secondary: '#6B7280',
      muted: '#9CA3AF',
      inverse: '#FFFFFF',
    },
    semantic: {
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
    border: {
      default: '#E5E7EB',
      hover: '#D1D5DB',
      focus: '#0066CC',
    },
    decorativeIcon: '#FBBF24',
  },
  gradients: [
    {
      name: 'primary',
      type: 'linear',
      angle: 135,
      stops: [
        { color: '#0066CC', position: 0 },
        { color: '#0052A3', position: 100 },
      ],
    },
    {
      name: 'hero',
      type: 'linear',
      angle: 135,
      stops: [
        { color: '#0066CC', position: 0 },
        { color: '#0052A3', position: 100 },
      ],
    },
    {
      name: 'accent',
      type: 'linear',
      angle: 90,
      stops: [
        { color: '#0066CC', position: 0 },
        { color: '#0052A3', position: 100 },
      ],
    },
  ],
  designTokens: {
    spacing: {
      '0': '0px',
      '1': '4px',
      '2': '8px',
      '3': '12px',
      '4': '16px',
      '5': '20px',
      '6': '24px',
      '8': '32px',
      '10': '40px',
      '12': '48px',
      '16': '64px',
      '20': '80px',
      '24': '96px',
      '32': '128px',
    },
    borderRadius: {
      none: '0px',
      sm: '4px',
      md: '8px',
      lg: '16px',
      xl: '24px',
      '2xl': '32px',
      full: '9999px',
    },
    shadows: {
      none: 'none',
      sm: '0 1px 2px rgba(0,0,0,0.05)',
      md: '0 4px 6px rgba(0,0,0,0.1)',
      lg: '0 10px 15px rgba(0,0,0,0.1)',
      xl: '0 20px 25px rgba(0,0,0,0.15)',
      '2xl': '0 25px 50px rgba(0,0,0,0.25)',
    },
    blur: {
      none: '0',
      sm: '4px',
      md: '8px',
      lg: '16px',
      xl: '24px',
    },
    opacity: {
      '0': 0,
      '25': 0.25,
      '50': 0.5,
      '75': 0.75,
      '100': 1,
    },
    borderWidth: {
      '0': '0px',
      '1': '1px',
      '2': '2px',
      '4': '4px',
      '8': '8px',
    },
    containerMaxWidth: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  },
  layouts: {
    navigation: {
      style: 'floating',
      position: 'top',
      transparent: true,
      blur: true,
      activeBackground: '#0066CC',
    },
    hero: {
      layout: 'split-screen',
      imagePosition: 'right',
      textAlign: 'left',
      gradient: true,
    },
    pages: {
      doctors: {
        layout: 'grid',
        columns: 3,
        cardStyle: 'elevated',
        spacing: '32px',
      },
      services: {
        layout: 'grid',
        columns: 3,
        cardStyle: 'icon-cards',
        spacing: '32px',
        iconSize: '48px',
      },
      testimonials: {
        layout: 'carousel',
        itemsVisible: 3,
        autoplay: true,
      },
      contact: {
        layout: 'split',
        mapPosition: 'right',
        formStyle: 'card',
      },
    },
    cards: {
      radius: '16px',
      shadow: 'md',
      padding: '24px',
      hoverEffect: 'lift',
      hoverScale: '1.02',
    },
    sections: {
      paddingY: '80px',
      maxWidth: '1280px',
      gutter: '32px',
    },
  },
  animations: {
    durations: {
      fast: '150ms',
      normal: '300ms',
      slow: '500ms',
      slower: '750ms',
    },
    easings: {
      default: 'cubic-bezier(0.4, 0, 0.2, 1)',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    delays: {
      none: '0ms',
      short: '100ms',
      medium: '200ms',
      long: '300ms',
    },
    features: {
      scrollReveal: true,
      hoverEffects: true,
      pageTransitions: true,
      reduceMotionRespect: true,
    },
  },
  accessibility: {
    highContrast: {
      enabled: false,
      textContrast: '7:1',
      borderContrast: '3:1',
    },
    focusIndicators: {
      style: 'outline',
      width: '2px',
      offset: '2px',
      color: '#4F86F7',
      contrast: '3:1',
    },
    reducedMotion: {
      respectPreference: true,
      fallbackDuration: '0ms',
    },
    keyboardNavigation: {
      skipLinks: true,
      focusVisible: true,
      tabIndex: true,
    },
    screenReader: {
      announcements: true,
      landmarkLabels: true,
      ariaLabels: true,
    },
    minimumTargetSize: '44px',
  },
  typography: {
    fontFamilies: {
      heading: 'Inter, Noto Sans Telugu, -apple-system, BlinkMacSystemFont, sans-serif',
      body: 'Inter, Noto Sans Telugu, -apple-system, BlinkMacSystemFont, sans-serif',
      mono: 'Menlo, Monaco, Consolas, monospace',
    },
    fontUrls: [
      'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap',
      'https://fonts.googleapis.com/css2?family=Noto+Sans+Telugu:wght@300;400;500;600;700&display=swap',
    ],
    fontSizes: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
      '5xl': '48px',
      '6xl': '60px',
      '7xl': '72px',
    },
    fontWeights: {
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
    },
    lineHeights: {
      tight: '1.2',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    fontLoadingStrategy: 'swap',
  },
  emergencyButton: {
    text: 'Emergency Call',
    backgroundColor: '#EF4444',
    textColor: '#FFFFFF',
  },
  backButton: {
    text: 'Back',
    backgroundColor: 'transparent',
    textColor: '',
    borderColor: '',
    hoverBackgroundColor: '',
    hoverTextColor: '',
  },
};

export const FALLBACK_THEME_NAME = 'Clinical Modern';
export const FALLBACK_THEME_DESCRIPTION = 'Emergency fallback theme with clean, modern medical design';
